<?php

return [
    'serviceName' => 'ViceSisters',
    'adminEmail' => 'admin@example.com',
    'managerEmail' => 'vicemanage@gmail.com',
    'managerPhone' => '+38 093 28 50 627',
    'managerSkype' => 'vice-manager',

    'dateTimeFormat' => 'Y-m-d H:i:s',
    'dateFormat' => 'Y-m-d',
    'timeFormat' => 'H:i:s',
    'defaultPageCount' => 10,
    'defaultAdminPageCount' => 15,
    'topPhotosCount' => 8,

    'defaultSessionTime' => 3600*24,
    'defaultCacheTime' => 3600*24,
    'rememberMeSessionTime' => 3600*24*30,

    'maxCacheTime' => 3600*24,
    'findOneCacheTime' => 300,
    'findAllCacheTime' => 300,
    'accountCacheTime' => 300,

    'userOnlineTime' => 300,
    'onlineTimeCheck' => 3600*2,
    'onlineRatingIncrementor' => 5,

    'escortAccountCacheTime' => 300,
    'topVipsCacheTime' => 300,
    'vipsCacheTime' => 300,
    'topProfilesCacheTime' => 300,
    'escortMessagesCacheTime' => 300,
    'escortLastMessageCacheTime' => 30,
    'lastVerifiedCacheTime' => 300,
    'escortPhotoGalleryCacheTime' => 300,
    'feedbackListCacheTime' => 300,
    'lastFeedbackCacheTime' => 30,
    'escortFeedsCacheTime' => 300,
    'feedMessageCacheTime' => 60,
    'userProfileCacheTime' => 300,
    'proplansCacheTime' => 3600*24*7,
    'membershipDurationCacheTime' => 3600*24,
    'userAvatarCacheTime' => 300,
    'userSearchSettingsCacheTime' => 300,
    'proplanDiscountCacheTime' => 10,
    'ProplanCacheTime' => 300,
    'userGeoCacheTime' => 3600*24,
    'randomImageCacheTime' => 300,
    'searchCacheTime' => 3600,
    'proplanMembersCacheTime' => 3600,
    'escortStatsCacheTime' => 3600*24,
    'feedMessagesListCacheTime' => 60,

    'topVipsLimit' => 250,
    'premiumAccountsLimit' => 5,
    'topProfilesLimit' => 10,
    'topProfilesListLimit' => 20,
    'hotMessagesLimit' => 4,
    'lastVerifiedLimit' => 6,
    'feedbackListLimit' => 4,
    'escortFeedsLimit' => 10,
    'escortFeedbacksLimit' => 3600*12,

    'escortImageLikeCount' => 1,
    'escortFeedLikeCount' => 2,

    'hotMessageCost' => 3,

    'vipPersonsHide' => 36500,
    'vipPersonsShow' => 37500,
    'lastVerifiedTime' => 35000,
    'lastHotMessageTime' => 33000,
    'lastFeedBackTime' => 5000,
];
